### ISSUE TITLE
Add PHP 8.4 support

### ISSUE THREAD

**Issue by kaszarobert** [lando/php#125]
Just like last year with 8.3 https://github.com/lando/php/issues/77

**Comment by reynoldsalec** [comment]
@kaszarobert looks like the 8.4 images are still in beta for the non-alpine images, so I may hold off on this PR, but got it rolling: https://github.com/lando/php/pull/128

**Comment by reynoldsalec** [comment]
...yeah checked back on this and I'm guessing we'll need to wait until next month's official release date for 8.4 (or after) for some of the dependencies to shake out.
