### ISSUE TITLE
Missing parsed ini Files in PHPStorm

### ISSUE THREAD

**Issue by benblub** [lando/php#13]
My example is showed with php 8.1 but its the same Problem with php 8.0 and i think other Versions too.

As you can see the XSL ini File is not loaded/parsed in Storm.

From Storm
![Bildschirmfoto 2021-12-22 um 15 22 38](https://user-images.githubusercontent.com/1756031/147107294-b3559d2a-468b-4559-9605-0850846199ff.png)

From SSH
![Bildschirmfoto 2021-12-22 um 15 24 22](https://user-images.githubusercontent.com/1756031/147107524-a6d282dd-b139-4be1-b29e-eca265777776.png)

**How to reproduce**
add to your lando yaml xsl `docker-php-ext-install xsl`.
Config the CLI Interpreter in Storm
done.

As you can see xdebug and other ini Files are working.

Some more tests
Via SSH CLI: `php -dextensiion=/usr/local/lib/php/extensions/no-debug-non-zts-20210902/xsl.so bin/phpunit` 
OK

Via Storm
```
[docker://devwithlando/php:8.1-apache-4/]:php -dextension=/usr/local/lib/php/extensions/no-debug-non-zts-20210902/xsl.so /app/vendor/phpunit/phpunit/phpunit 
Testing started at 15:44 ...

Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20210902/xsl.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20210902/xsl.so (/usr/local/lib/php/extensions/no-debug-non-zts-20210902/xsl.so: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20210902//usr/local/lib/php/extensions/no-debug-non-zts-20210902/xsl.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20210902//usr/local/lib/php/extensions/no-debug-non-zts-20210902/xsl.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

**Comment by labboy0276** [comment]
@benblub Are you saying if we add `docker-php-ext-install xsl` to our docker container for these php images, it will fix the issue?

**Comment by benblub** [comment]
Sounds like a solution. Would be nice to give it a try 👍

**Comment by benblub** [comment]
Some more Infos
> Yes, PhpStorm doesn't run exec against Docker images, this is not supported yet, unfortunately. It runs an image every time you call some script or run configuration in IDE. Looks like some configuration/customization is being made to the Docker image after it is up with docker run & PhpStorm is unable to replicate these configuration changes. Not it is able to connect to to a modified image via exec.
So, how is XSL installed/enabled during or after Docker image build process?

**Comment by benblub** [comment]
some Update. I tried the extend image solution. This fixed the Issue 💪  

https://docs.lando.dev/guides/installing-php-extensions-on-lando.html#_2-using-dockerfiles

**Comment by labboy0276** [comment]
OK @benblub 

Can you post your solution here so others can see.

**Comment by benblub** [comment]
you need do 2 things.

Edit your lando.yml like this
```yaml
        type: php:custom
        overrides:
            image: lando/php:8.1-apache-4
            build:
                context: ./
                dockerfile: Dockerfile.custom
```                


Dockerfile.custom
```Dockerfile
FROM devwithlando/php:8.1-apache-4

# Add php extension helper
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

# Install XSL Extension
RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
  install-php-extensions xsl
```

The docker-php-extension-installer has many extensions available. If there is something missing you have to install/config it by yourself.

**Comment by labboy0276** [comment]
@benblub OK, that is how we do it pretty much on one of our tests as well: https://github.com/lando/php/tree/main/examples/php-extensions

I will close this out, but this will stay as reference for other peoples who have this issue.
