### ISSUE TITLE
ERROR ==> php version 8.1.29 is not supported

### ISSUE THREAD

**Issue by Taiger** [lando/php#140]
It appears that minor version differences of php are not supported when using Lando.
This means I cannot replicate other server environments on my local and defeats the whole purpose of using Docker containers for development.

Is there a way to make this work, while still using Lando?

**Comment by reynoldsalec** [comment]
https://docs.lando.dev/plugins/php/#patch-versions

Basically you'd need to create a custom service. Note that patch versions will be supported once the v4 API version of the PHP plugin comes out.

**Comment by Taiger** [comment]
Thank you!
