### ISSUE TITLE
Support imagick for php 8.0 & 8.1

### ISSUE THREAD

**Issue by benblub** [lando/php#15]
Any reason why this is not supported yet?

As i can see [there ](https://github.com/mlocati/docker-php-extension-installer) its working

**Comment by labboy0276** [comment]
@benblub all our php 8+ imaghes have imagemagick library installed and the imagick extension enabled: https://github.com/lando/php/blob/main/images/8.0-fpm/Dockerfile

What particular problem are you facing?

**Comment by benblub** [comment]
ok i didnt tested. Just seen in the docs its not supported https://docs.lando.dev/config/php.html#installed-extensions

**Comment by labboy0276** [comment]
Yeah we need to update those @benblub
