### ISSUE TITLE
Remove hirak/presstisimo from PHP7.4, use composer 2 by default

### ISSUE THREAD

**Issue by delboy1978uk** [lando/php#3]
Lots of PHP7.4 sites are using composer 2. We always get this error regarding a composer 1 plugin:

![image](https://user-images.githubusercontent.com/2684575/146799655-88f4320d-08da-4f39-bd95-482a921543e4.png)

Can we make the PHP7.4 image use composer v2, and remove the need for `hirak/presstisimo` ? It has been done for the 8.0 and 8.1 images

**Comment by delboy1978uk** [comment]
https://github.com/lando/lando/issues/3176

**Comment by delboy1978uk** [comment]
https://github.com/lando/lando/issues/2726

**Comment by delboy1978uk** [comment]
https://github.com/lando/php/pull/4

**Comment by labboy0276** [comment]
This has been merged in via https://github.com/lando/php/pull/14

**Comment by labboy0276** [comment]
Thank you @delboy1978uk

**Comment by delboy1978uk** [comment]
Thanks @labboy0276 :-D have a great Christmas!

**Comment by labboy0276** [comment]
You as well
