### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by gitressa** [lando/php#40]
[PHP 8.2](https://github.com/drush-ops/drush/issues/5168) is coming, so it would be great if it got Lando support at some point.

**Comment by andypost** [comment]
There's official images to start with https://hub.docker.com/_/php?tab=tags&page=1&name=8.2

**Comment by allanlaal** [comment]
Lando worked great with PHP 8.1, so 8.2 won't require any fixes to run

**Comment by kaszarobert** [comment]
I started a PR #49 
Please review if the Dockerfiles and other configurations are OK.

**Comment by reynoldsalec** [comment]
...PHP 8.2 was added back in April, yay!

**Comment by andypost** [comment]
Now it's time for PHP 8.3 as rc5 is out

**Comment by kaszarobert** [comment]
Let's solve 8.3 in a different issue: https://github.com/lando/php/issues/77
