### ISSUE TITLE
Why should Lando enable MultiViews, which is disabled by Apache default?

### ISSUE THREAD

**Issue by mochiya-hemmi** [lando/php#66]
### Why "Options Indexes FollowSymLinks MultiViews" ?

I built a Drupal site with Lando and created a page called /example, but I got an Apache 404 Not Found.
This is because the "example.gitignore" file exists directly under the document root, and the MultiViews could not find the extension "gitignore".
By the way, ".htaccess" does not have a description to enable MultiViews. After some research, I found that MultiViews was enabled in Apache's VirtualHost options.

https://github.com/lando/php/blob/77e0c6982878ad829fd55a5ea2d83a9f95eb6ffa/services/php/default-ssl.conf#L15
https://github.com/lando/php/blob/77e0c6982878ad829fd55a5ea2d83a9f95eb6ffa/services/php/default-ssl.conf#L51
https://github.com/lando/php/blob/77e0c6982878ad829fd55a5ea2d83a9f95eb6ffa/services/php/default.conf#L15

I looked at https://httpd.apache.org/docs/current/en/mod/core.html#Options to see what the Apache defaults are for this, but it seems that the only default value is ``Options FollowSymlinks``.

I'm not sure why you needed to enable MultiViews, but at least it's hurting Drupal development.

I hope you can improve.
thank you.

**Comment by reynoldsalec** [comment]
@pirog you know any reasons why this is in the default apache config for PHP?

I think Drupal does have some .htaccess rules to disable MultiViews under certain circumstances (like hardening access to files), and it looks like some other projects disable MultiViews for PHP CGI.

**Comment by reynoldsalec** [comment]
...looks like there's an older issue this duplicates: https://github.com/lando/lando/issues/3139

Also found another instance where having MultiViews enabled caused some confusion: https://github.com/lando/apache/issues/20

**Comment by reynoldsalec** [comment]
Doing further research on this, it sounds like the default Apache conf in Lando's PHP plugin is legacy from some default @pirog found a LONG time ago.

My research seems to indicate that most default confs either don't include MultiViews or disable it explicitly, as you expressed @mochiya-hemmi.

I think if we just drop MultiViews from the config, it'll be disabled by other config already in the PHP images. Created a PR to that effect and will test a bit.

**Comment by reynoldsalec** [comment]
@mochiya-hemmi this should be resolved as of PHP v0.10.0, which will be available in Lando releases going forward. If you want to try installing the latest PHP version, you can manually install it using the "Docker" instructions: https://docs.lando.dev/php/#custom-installation
