### ISSUE TITLE
Windows10 Pro lando drush issue

### ISSUE THREAD

**Issue by UrielNicolas** [lando/php#9]
Basically any other task or issue should go here. Try to frame it as a user story if it makes sense.
I'm trying to make Lando work in Windows10
I was able to install lando, it actually works, but I have issues with Drush

`OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec format error": unknown`

This is my .lando.yml
`
name: sitename
recipe: pantheon
config:
  webroot: web
  framework: drupal8
  site: sitename
  id: ID
tooling:
  local-load-db:
    service: appserver
    description: Load database
    cmd: /app/local/import.sh
    level: app
`

I'm not sure what the issue is, and I've been trying to find out what is happening, but I have no idea.

I also have issues at running our local scripts, but unless Drush works first, it's futile.

**Comment by simonmerrell** [comment]
Many thanks to the contributors to this thread. I'm having a very similar problem with Drush. I'm using Win10 + WSL2 + Ubuntu 18.04 and working on a Drupal 9 project.

Thanks to your suggestions, I have a working Drush command now, and my recipe is:

name: project
recipe: drupal9
config:
  php: '8.0'
  webroot: project/web

tooling:
  drush:
    service: appserver
    cmd: php "project/web/vendor/drush/drush/drush"
    env:
      DRUSH_OPTIONS_URI: "https://project.lndo.site"


I assume this cmd will need to be removed for the Mac OS collaborators on my project.

**Comment by UnsettlingTrend** [comment]
Lando was working just fine with Drush.... until it wasn't. For some reason, just adding the `php` to `php 'app/vendor/bin/drush'` did the trick on Win10.

**Comment by zuernBernhard** [comment]
Yes same here too after upgrading Lando and docker 

works:

`lando php /app/vendor/bin/drush cr`

does not work: 

`$ lando drush cr
OCI runtime exec failed: exec failed: unable to start container process: exec: "/app/vendor/bin/drush": permission denied: unknown`

**Comment by zuernBernhard** [comment]
Update: I could make it work again by deleting everything which was installed by composer and do a 

`lando composer install `

after that

**Comment by AaronFeledy** [comment]
Since this ticket was opened, there have been a number of improvements in handling the various scenarios mentioned in this thread. Given that it has been 18 months without any new comments here, I'm going to close this out and assume that Lando is now working as expected for everyone. If there is anything that still needs addressing, please open a new issue.
